### ISSUE TITLE
Arata bine

### ISSUE THREAD

**Issue by GheorgheCazacu** [AndreiOvidiuCiobanu/CarService#1]
Proiectul arata bine, ati implementat cerintele.
Pe viitor putem adauga la el alte functionalitati.

O zi frumoasa
PS
Nu v-am intrebat la laborator dar la fmi aveti un curs ceva de modelare obiectuala?

**Comment by AndreiOvidiuCiobanu** [comment]
Buna ziua!
Multumesc!

Legat de intrebare, din ce stiu eu nu avem asa ceva, anul viitor se va schimba putin programa, insa in prezent, nu stiu de existenta unui astfel de curs.
